# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineSearch = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSearch.setObjectName("lineSearch")
        self.gridLayout.addWidget(self.lineSearch, 0, 0, 1, 1)
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setObjectName("btn_search")
        self.gridLayout.addWidget(self.btn_search, 0, 7, 1, 1)
        self.toolFilter = QtWidgets.QToolButton(self.centralwidget)
        self.toolFilter.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolFilter.setObjectName("toolFilter")
        self.gridLayout.addWidget(self.toolFilter, 0, 4, 1, 1)
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGridStyle(QtCore.Qt.SolidLine)
        self.table.setRowCount(5)
        self.table.setColumnCount(5)
        self.table.setObjectName("table")
        self.table.horizontalHeader().setVisible(True)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setDefaultSectionSize(150)
        self.gridLayout.addWidget(self.table, 1, 0, 1, 8)
        self.btn_cad = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cad.sizePolicy().hasHeightForWidth())
        self.btn_cad.setSizePolicy(sizePolicy)
        self.btn_cad.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_cad.setSizeIncrement(QtCore.QSize(0, 0))
        self.btn_cad.setBaseSize(QtCore.QSize(0, 0))
        self.btn_cad.setObjectName("btn_cad")
        self.gridLayout.addWidget(self.btn_cad, 2, 7, 1, 1)
        self.btn_refresh = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_refresh.sizePolicy().hasHeightForWidth())
        self.btn_refresh.setSizePolicy(sizePolicy)
        self.btn_refresh.setSizeIncrement(QtCore.QSize(0, 0))
        self.btn_refresh.setObjectName("btn_refresh")
        self.gridLayout.addWidget(self.btn_refresh, 2, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Produtos"))
        self.btn_search.setText(_translate("MainWindow", "Pesquisar"))
        self.toolFilter.setText(_translate("MainWindow", "Filtros"))
        self.table.setSortingEnabled(False)
        self.btn_cad.setText(_translate("MainWindow", "Cadastrar novo produto"))
        self.btn_refresh.setText(_translate("MainWindow", "Atualizar"))
