# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setStyleSheet("")
        self.table.setGridStyle(QtCore.Qt.SolidLine)
        self.table.setRowCount(5)
        self.table.setColumnCount(5)
        self.table.setObjectName("table")
        self.table.horizontalHeader().setVisible(True)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setDefaultSectionSize(150)
        self.gridLayout.addWidget(self.table, 1, 0, 1, 9)
        self.toolFilter = QtWidgets.QToolButton(self.centralwidget)
        self.toolFilter.setStyleSheet("QToolButton {\n"
"                background: #76afcc; \n"
"                color: #fff; \n"
"                font: Times New Roman; \n"
"                font-size: 12px; \n"
"                font-weight: 700; \n"
"                border-radius: 5px; \n"
"                height: 20px;\n"
"                width: 100%;\n"
"                padding: 0 15px;\n"
"            }\n"
"\n"
"            QToolButton:hover {\n"
"                background: #81b2eb;\n"
"            }")
        self.toolFilter.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolFilter.setObjectName("toolFilter")
        self.gridLayout.addWidget(self.toolFilter, 0, 7, 1, 1)
        self.lineSearch = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSearch.setStyleSheet("QLineEdit {\n"
"                background: white;\n"
"                height: 25px;\n"
"                border: 1px solid #474747;\n"
"                border-radius: 2px;\n"
"                font-size: 14px;\n"
"                font: sans-serif;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 1px solid #23a5c2;\n"
"            }")
        self.lineSearch.setObjectName("lineSearch")
        self.gridLayout.addWidget(self.lineSearch, 0, 0, 1, 7)
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setStyleSheet("QPushButton {\n"
"                background: #3C8FBC; \n"
"                color: #fff; \n"
"                font: Times New Roman; \n"
"                font-size: 12px; \n"
"                font-weight: 700; \n"
"                border-radius: 5px; \n"
"                height: 25px;\n"
"                padding: 5rem;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                background: #81b2eb;\n"
"            }")
        self.btn_search.setObjectName("btn_search")
        self.gridLayout.addWidget(self.btn_search, 0, 8, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"                background: #d16969; \n"
"                color: #fff; \n"
"                font: Times New Roman; \n"
"                font-size: 12px; \n"
"                font-weight: 700; \n"
"                border-radius: 5px; \n"
"                height: 30px;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                background: #cf8686;\n"
"            }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setStyleSheet("QPushButton {\n"
"                background: #3C8FBC; \n"
"                color: #fff; \n"
"                font: Times New Roman; \n"
"                font-size: 12px; \n"
"                font-weight: 700; \n"
"                border-radius: 5px; \n"
"                height: 30px;\n"
"                padding: 0 5px;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                background: #81b2eb;\n"
"            }")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 2)
        self.btn_cad = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cad.sizePolicy().hasHeightForWidth())
        self.btn_cad.setSizePolicy(sizePolicy)
        self.btn_cad.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_cad.setSizeIncrement(QtCore.QSize(0, 0))
        self.btn_cad.setBaseSize(QtCore.QSize(0, 0))
        self.btn_cad.setStyleSheet("QPushButton {\n"
"                background: #229440; \n"
"                color: #fff; \n"
"                font: Times New Roman; \n"
"                font-size: 12px; \n"
"                font-weight: 700; \n"
"                border-radius: 5px; \n"
"                height: 30px;\n"
"                padding: 0 10px;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                background: #8ac298;\n"
"            }")
        self.btn_cad.setObjectName("btn_cad")
        self.gridLayout.addWidget(self.btn_cad, 2, 7, 1, 2)
        self.btn_refresh = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_refresh.sizePolicy().hasHeightForWidth())
        self.btn_refresh.setSizePolicy(sizePolicy)
        self.btn_refresh.setSizeIncrement(QtCore.QSize(0, 0))
        self.btn_refresh.setStyleSheet("QPushButton {\n"
"                background: #3C8FBC; \n"
"                color: #fff; \n"
"                font: Times New Roman; \n"
"                font-size: 12px; \n"
"                font-weight: 700; \n"
"                border-radius: 5px; \n"
"                height: 30px;\n"
"                padding: 0 5px;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                background: #81b2eb;\n"
"            }")
        self.btn_refresh.setObjectName("btn_refresh")
        self.gridLayout.addWidget(self.btn_refresh, 3, 7, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Produtos"))
        self.table.setSortingEnabled(False)
        self.toolFilter.setText(_translate("MainWindow", "Filtros"))
        self.btn_search.setText(_translate("MainWindow", "Pesquisar"))
        self.pushButton_2.setText(_translate("MainWindow", "Excluir"))
        self.pushButton.setText(_translate("MainWindow", "Editar"))
        self.btn_cad.setText(_translate("MainWindow", "Cadastrar novo produto"))
        self.btn_refresh.setText(_translate("MainWindow", "Atualizar"))
