# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'venda.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_venda(object):
    def setupUi(self, form_venda):
        form_venda.setObjectName("form_venda")
        form_venda.resize(870, 630)
        self.gridLayout = QtWidgets.QGridLayout(form_venda)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_add = QtWidgets.QPushButton(form_venda)
        self.btn_add.setStyleSheet("QPushButton {\n"
"                background: #3C8FBC; \n"
"                color: #fff; \n"
"                font: Times New Roman; \n"
"                font-size: 12px; \n"
"                font-weight: 700; \n"
"                border-radius: 5px; \n"
"                height: 30px;\n"
"                width: 150px;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                background: #81b2eb;\n"
"            }")
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_2.addWidget(self.btn_add)
        self.pushButton = QtWidgets.QPushButton(form_venda)
        self.pushButton.setStyleSheet("QPushButton {\n"
"                background: #d16969; \n"
"                color: #fff; \n"
"                font: Times New Roman; \n"
"                font-size: 12px; \n"
"                font-weight: 700; \n"
"                border-radius: 5px; \n"
"                height: 30px;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                background: #cf8686;\n"
"            }")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_finish = QtWidgets.QPushButton(form_venda)
        self.btn_finish.setStyleSheet("QPushButton {\n"
"                background: #408552; \n"
"                color: #fff; \n"
"                font: Times New Roman; \n"
"                font-size: 12px; \n"
"                font-weight: 700; \n"
"                border-radius: 5px; \n"
"                height: 30px;\n"
"                width: 122px;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                background: #4d945f;\n"
"            }")
        self.btn_finish.setObjectName("btn_finish")
        self.gridLayout_2.addWidget(self.btn_finish, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.btn_cancel = QtWidgets.QPushButton(form_venda)
        self.btn_cancel.setStyleSheet("QPushButton {\n"
"                background: #d16969; \n"
"                color: #fff; \n"
"                font: Times New Roman; \n"
"                font-size: 12px; \n"
"                font-weight: 700; \n"
"                border-radius: 5px; \n"
"                height: 30px;\n"
"                width: 122px;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                background: #cf8686;\n"
"            }")
        self.btn_cancel.setObjectName("btn_cancel")
        self.gridLayout_2.addWidget(self.btn_cancel, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 6, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(650, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(form_venda)
        self.label.setStyleSheet("font-size: 12pt\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.line_total = QtWidgets.QLineEdit(form_venda)
        self.line_total.setStyleSheet("QLineEdit {\n"
"                background: white;\n"
"                height: 25px;\n"
"                border: 1px solid #474747;\n"
"                border-radius: 2px;\n"
"                font-size: 14px;\n"
"                font: sans-serif;\n"
"                width: 120px;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 1px solid #23a5c2;\n"
"            }")
        self.line_total.setObjectName("line_total")
        self.horizontalLayout.addWidget(self.line_total)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(form_venda)
        self.tableWidget.setStyleSheet("font: 11pt arial;\n"
"color: #434343;\n"
"font-weight: 450;\n"
"alternate-background-color: rgb(232, 232, 232);\n"
"\n"
"")
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(166)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget, 4, 0, 1, 1)

        self.retranslateUi(form_venda)
        QtCore.QMetaObject.connectSlotsByName(form_venda)

    def retranslateUi(self, form_venda):
        _translate = QtCore.QCoreApplication.translate
        form_venda.setWindowTitle(_translate("form_venda", "Nova venda"))
        self.btn_add.setText(_translate("form_venda", "Adicionar produto"))
        self.pushButton.setText(_translate("form_venda", "Excluir produto da venda"))
        self.btn_finish.setText(_translate("form_venda", "Finalizar venda"))
        self.btn_cancel.setText(_translate("form_venda", "Cancelar"))
        self.label.setText(_translate("form_venda", "Total: R$"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("form_venda", "Código"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("form_venda", "Descrição"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("form_venda", "Preço Unit."))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("form_venda", "Quantidade"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("form_venda", "Total"))
