# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from banco import Banco
from cadastro import *
from PyQt5.QtWidgets import QMainWindow, QApplication, QDialog
from PyQt5.QtCore import Qt
from PyQt5 import QtGui

class Ui_MainWindow(object):
    def dados(self):
        banco = Banco("./database/dados.db")
        self.result = banco.consulta("Produtos")
        self.collumn = len(self.result[0])
        self.row = len(self.result)
        self.table.setRowCount(0)
        self.table.setColumnCount(self.collumn)
        self.table.setColumnWidth(0, 60)
        self.table.setColumnWidth(1, 380)
        self.table.setColumnWidth(2, 120)
        for row_number, row_data in enumerate(self.result):
            self.table.insertRow(row_number)
            for collumn_number, data in enumerate(row_data):
                
                if collumn_number == 2:
                    valor = (f"R$ {data:.2f}")
                    self.item = QtWidgets.QTableWidgetItem(str(valor).replace(".", ","))
                elif collumn_number == 0:
                    valor = (f"{data:0>4}")
                    self.item = QtWidgets.QTableWidgetItem(str(valor))
                else:
                    self.item = QtWidgets.QTableWidgetItem(str(data))
                if collumn_number == 0 or collumn_number == 2:
                    self.item.setTextAlignment(Qt.AlignRight)
                else:
                    self.item.setTextAlignment(Qt.AlignLeft)
                self.table.setItem(row_number, collumn_number, self.item)
    
    def openCad(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow2()
        self.ui.setupUi(self.window)
        self.window.show()
        self.ui.btn_cancel.clicked.connect(self.window.close)
        self.window.setWindowTitle("Cadastro de novo Produto")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        #self.centralwidget.setStyleSheet("background-color: #d6d6d6")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_cad = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cad.setObjectName("btn_cad")
        #self.btn_cad.clicked.connect(QApplication.exit)
        self.gridLayout.addWidget(self.btn_cad, 1, 1, 1, 1)
        self.btn_cad.clicked.connect(self.openCad)
        self.btn_cad.setStyleSheet("""
            QPushButton {
                background: #61AB6D; 
                color: #fff; 
                font: Times New Roman; 
                font-size: 14px; 
                font-weight: 700; 
                border-radius: 5px; 
                height: 30px;
            }

            QPushButton:hover {
                background: #72bd6c;
            }
            """
        )
        self.btn_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.btn_refresh.setObjectName("btn_refresh")
        self.btn_refresh.clicked.connect(self.dados)
        self.btn_refresh.setStyleSheet(
            """
            QPushButton {
                background: #3C8FBC; 
                color: #fff; 
                font: Times New Roman; 
                font-size: 14px; 
                font-weight: 700; 
                border-radius: 5px; 
                height: 30px
            }

            QPushButton:hover {
                background: #81b2eb;
            }
            """
        )
        self.gridLayout.addWidget(self.btn_refresh, 1, 0, 1, 1)
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGridStyle(QtCore.Qt.SolidLine)
        self.table.setRowCount(0)
        self.table.setColumnCount(0)
        self.table.setObjectName("table")
        self.table.horizontalHeader().setVisible(True)
        self.table.verticalHeader().setVisible(False)
        self.table.horizontalHeader().setCascadingSectionResizes(True)
        self.table.horizontalHeader().setDefaultSectionSize(200)
        self.table.horizontalHeader().setStyleSheet("background: white; font: arial; font-size: 14px; font-weight: 500")
        self.table.setStyleSheet(
            """
                QTableView {
                    background: white;
                    color: #292929;
                    font-size: 16px;
                    font: arial;
                    font-weight: 400;
                }
            """
        )

        self.gridLayout.addWidget(self.table, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.dados()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Produtos"))
        self.btn_cad.setText(_translate("MainWindow", "Cadastrar novo produto"))
        self.btn_refresh.setText(_translate("MainWindow", "Atualizar"))
        self.table.setSortingEnabled(False)
        self.table.setHorizontalHeaderLabels(["Código", "Descrição", "Valor Unitário", "Tipo"])
        #self.table.horizontalHeaderItem(3).setTextAlignment(Qt.AlignHCenter)
